version: '3'
services:
  frontend:
    image: sayeem9090/eshop-frontend:latest
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
